### ISSUE TITLE
NumbaTypeError in getLGP

### ISSUE THREAD

**Issue by antony-john-payne** [gicait/PyAEZ#83]
Hi

I get the following numba error when running getLGP

>>> lgp = clim_reg.getLGP(Sa=100, D=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/user/home/ggajp/.conda/envs/myaez/lib/python3.11/site-packages/pyaez/ClimateRegime.py", line 496, in getLGP
    self.meanT_daily_new[i_row, i_col, :], istart0, istart1 = LGPCalc.rainPeak(totalPrec_monthly, meanT_daily_point, lgpt5_point)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/ggajp/.conda/envs/myaez/lib/python3.11/site-packages/numba/core/dispatcher.py", line 733, in typeof_pyval
    tp = typeof(val, Purpose.argument)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/ggajp/.conda/envs/myaez/lib/python3.11/site-packages/numba/core/typing/typeof.py", line 33, in typeof
    ty = typeof_impl(val, c)
         ^^^^^^^^^^^^^^^^^^^
  File "/user/home/ggajp/.conda/envs/myaez/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/ggajp/.conda/envs/myaez/lib/python3.11/site-packages/numba/core/typing/typeof.py", line 244, in _typeof_ndarray
    raise errors.NumbaTypeError(msg)
numba.core.errors.NumbaTypeError: Unsupported array type: numpy.ma.MaskedArray.

I think that I am using the latest version of pyaez 

# packages in environment at /user/home/ggajp/.conda/envs/myaez:
#
# Name                    Version                   Build  Channel
pyaez                     2.1                pyhd8ed1ab_0    conda-forge

Any ideas?

Thanks
tony

**Comment by antony-john-payne** [comment]
Hi again

Strangely I find that adding tt = lgpt5_point.data between the creation of lgpt5_point and its use in LGPCalc.rainPeak solves the problem. Lines 492-500 of  ClimateRegime.py

                lgpt5_point = self.lgpt5[i_row, i_col]

                totalPrec_monthly = UtilitiesCalc.UtilitiesCalc().averageDailyToMonthly(self.totalPrec_daily[i_row, i_col, :])
                meanT_daily_point = Ta365[i_row, i_col, :]
                
                tt = lgpt5_point.data
                
                self.meanT_daily_new[i_row, i_col, :], istart0, istart1 = LGPCalc.rainPeak(
                    totalPrec_monthly, meanT_daily_point, lgpt5_point)

**Comment by NokuzaSezo97** [comment]
Dear @antony-john-payne,

We will check it out. Can you provide the version of python, numpy and numba for debugging? Thanks.

Regards,

Swun Wunna Htet

**Comment by xfry-lixuan** [comment]
**numba == 0.56.3** maybe can Solving Your Problems

**Comment by antony-john-payne** [comment]
Hi

Thanks for your reply and sorry about the delay in replying. I am on holiday.

The problem has gone away although I don’t understand why.  Here is the conda environment that I use:

(myaez) ~ : conda list
# packages in environment at /user/home/ggajp/.conda/envs/myaez:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
affine                    2.3.0              pyhd3eb1b0_0
alabaster                 0.7.12             pyhd3eb1b0_0
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
appdirs                   1.4.4              pyhd3eb1b0_0
arrow                     1.2.3           py311h06a4308_1
astroid                   2.14.2          py311h06a4308_0
asttokens                 2.0.5              pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     22.1.0          py311h06a4308_0
autopep8                  1.6.0              pyhd3eb1b0_1
babel                     2.11.0          py311h06a4308_0
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
binaryornot               0.4.4              pyhd3eb1b0_1
black                     23.3.0          py311h06a4308_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
blosc                     1.21.4               h0f2a231_0    conda-forge
boost-cpp                 1.78.0               h6582d0a_3    conda-forge
bottleneck                1.3.5           py311hbed6279_0
branca                    0.6.0           py311h06a4308_0
brotli                    1.0.9                h5eee18b_7
brotli-bin                1.0.9                h5eee18b_7
brotlipy                  0.7.0           py311h5eee18b_1002
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.19.0               h5eee18b_0
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cachetools                4.2.2              pyhd3eb1b0_0
cairo                     1.16.0               hb05425b_5
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h5eee18b_3
cfitsio                   4.2.0                hd9d235c_0    conda-forge
cftime                    1.6.2           py311hbed6279_0
chardet                   4.0.0           py311h06a4308_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4           py311h06a4308_0
click-plugins             1.1.1              pyhd3eb1b0_0
cligj                     0.7.2              pyhd3eb1b0_0
cloudpickle               2.2.1           py311h06a4308_0
colorama                  0.4.6           py311h06a4308_0
comm                      0.1.2           py311h06a4308_0
contourpy                 1.0.5           py311hdb19cb5_0
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              41.0.2          py311h22a60cf_0
curl                      8.1.2                h409715c_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0
dbus                      1.13.18              hb2f20db_0
debugpy                   1.5.1           py311h6a678d5_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.6           py311h06a4308_0
docstring-to-markdown     0.11            py311h06a4308_0
docutils                  0.18.1          py311h06a4308_3
entrypoints               0.4             py311h06a4308_0
executing                 0.8.3              pyhd3eb1b0_0
expat                     2.5.0                hcb278e6_1    conda-forge
fiona                     1.9.4           py311hbac4ec9_0    conda-forge
flake8                    6.0.0           py311h06a4308_0
folium                    0.14.0          py311h06a4308_0
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                hd3eb1b0_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-anaconda            1                    h8fa9717_0
fonts-conda-ecosystem     1                    hd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               h4a9f257_0
freexl                    1.0.6                h27cfd23_0
gdal                      3.7.0           py311h1caf18b_3    conda-forge
geocube                   0.4.2              pyhd8ed1ab_1    conda-forge
geopandas                 0.13.2             pyhd8ed1ab_1    conda-forge
geopandas-base            0.13.2             pyha770c72_1    conda-forge
geos                      3.11.2               hcb278e6_0    conda-forge
geotiff                   1.7.1                h22adcc9_9    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h5eee18b_3
glib                      2.76.3               hfc55251_0    conda-forge
glib-tools                2.76.3               hfc55251_0    conda-forge
graphite2                 1.3.14               h295c915_1
gst-plugins-base          1.22.3               he621ea3_0
gstreamer                 1.22.3               h5eee18b_0
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
hdf4                      4.2.15               h501b40f_6    conda-forge
hdf5                      1.14.1          nompi_h4f84152_100    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4             py311h06a4308_0
imagesize                 1.4.1           py311h06a4308_0
importlib-metadata        6.0.0           py311h06a4308_0
importlib_metadata        6.0.0                hd3eb1b0_0
inflection                0.5.1           py311h06a4308_0
intel-openmp              2023.1.0         hdb19cb5_46305
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.19.2          py311h6410fe4_0
ipython                   8.12.0          py311h06a4308_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
isort                     5.9.3              pyhd3eb1b0_0
jaraco.classes            3.2.1              pyhd3eb1b0_0
jedi                      0.18.1          py311h06a4308_1
jeepney                   0.7.1              pyhd3eb1b0_0
jellyfish                 0.9.0           py311h5eee18b_0
jinja2                    3.1.2           py311h06a4308_0
jinja2-time               0.2.0              pyhd3eb1b0_3
joblib                    1.2.0           py311h06a4308_0
json-c                    0.16                 h5eee18b_0
jsonschema                4.17.3          py311h06a4308_0
jupyter_client            8.1.0           py311h06a4308_0
jupyter_core              5.3.0           py311h06a4308_0
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
kealib                    1.5.1                h3e6883b_4    conda-forge
keyring                   23.13.1         py311h06a4308_0
kiwisolver                1.4.4           py311h6a678d5_0
krb5                      1.20.1               h143b758_1
lame                      3.100                h7b6447c_0
lazy-object-proxy         1.6.0           py311h5eee18b_0
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.38                 h1181459_1
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libarchive                3.6.2                h039dbb9_1    conda-forge
libbrotlicommon           1.0.9                h5eee18b_7
libbrotlidec              1.0.9                h5eee18b_7
libbrotlienc              1.0.9                h5eee18b_7
libcap                    2.67                 he9d0100_0    conda-forge
libclang                  16.0.6          default_h1cdf331_0    conda-forge
libclang13                16.0.6          default_h4d60ac6_0    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libcurl                   8.1.2                h409715c_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20221030         h5eee18b_0
libev                     4.33                 h7f8727e_1
libevent                  2.1.12               hdbd6064_1
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.4                h6a678d5_0
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgdal                   3.7.0                h4a547c6_3    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.3               hebfc3b9_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libgpg-error              1.47                 h71f35ed_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
libkml                    1.3.0             h37653c0_1015    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libllvm16                 16.0.6               h5cf9203_0    conda-forge
libnetcdf                 4.9.2           nompi_h78c856c_106    conda-forge
libnghttp2                1.52.0               h2d74bed_1
libnsl                    2.0.0                h5eee18b_0
libogg                    1.3.5                h27cfd23_1
libopus                   1.3.1                h7b6447c_0
libpng                    1.6.39               h5eee18b_0
libpq                     15.3                 hbcd7760_1    conda-forge
librttopo                 1.1.0               h0d5128d_13    conda-forge
libsndfile                1.2.0                hb75c966_0    conda-forge
libsodium                 1.0.18               h7b6447c_0
libspatialindex           1.9.3                h2531618_0
libspatialite             5.0.1               hca56755_27    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.10.0               hdbd6064_2
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libsystemd0               253                  h8c4010b_1    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h7b6447c_0
libwebp                   1.3.1                hbf2b3c1_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h7f8727e_0
libxkbcommon              1.5.0                h5d7e998_3    conda-forge
libxml2                   2.11.4               h0d562d8_0    conda-forge
libxslt                   1.1.37               h0054252_1    conda-forge
libzip                    1.9.2                hc929e4a_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.40.1          py311ha6695c7_0    conda-forge
lxml                      4.9.3           py311h1a07684_0    conda-forge
lz4-c                     1.9.4                h6a678d5_0
lzo                       2.10                 h7b6447c_2
mapclassify               2.5.0           py311h06a4308_0
markupsafe                2.1.1           py311h5eee18b_0
matplotlib-base           3.7.1           py311ha02d727_1
matplotlib-inline         0.1.6           py311h06a4308_0
mccabe                    0.7.0              pyhd3eb1b0_0
mistune                   0.8.4           py311h5eee18b_1000
mkl                       2023.1.0         h6d00ec8_46342
mkl-service               2.4.0           py311h5eee18b_1
mkl_fft                   1.3.6           py311ha02d727_1
mkl_random                1.2.2           py311ha02d727_1
more-itertools            8.12.0             pyhd3eb1b0_0
mpg123                    1.31.3               hcb278e6_0    conda-forge
munch                     2.5.0              pyhd3eb1b0_0
munkres                   1.1.4                      py_0
mypy_extensions           0.4.3           py311h06a4308_1
mysql-common              8.0.33               hf1915f5_1    conda-forge
mysql-libs                8.0.33               hca2cd23_1    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert                 6.5.4           py311h06a4308_0
nbformat                  5.7.0           py311h06a4308_0
ncurses                   6.4                  h6a678d5_0
nest-asyncio              1.5.6           py311h06a4308_0
netcdf4                   1.6.4           nompi_py311h9a7c333_101    conda-forge
networkx                  2.8.4           py311h06a4308_1
nspr                      4.35                 h6a678d5_0
nss                       3.89.1               h6a678d5_0
numba                     0.57.1          py311h96b013e_0    conda-forge
numexpr                   2.8.4           py311h65dcdc2_1
numpy                     1.24.3          py311h08b1b3b_1
numpy-base                1.24.3          py311hf175353_1
numpydoc                  1.5.0           py311h06a4308_0
odc-geo                   0.4.1              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.1                hd590300_1    conda-forge
packaging                 23.0            py311h06a4308_0
pandas                    1.5.3           py311hba01205_0
pandoc                    2.12                 h06a4308_3
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pathspec                  0.10.3          py311h06a4308_0
pcre2                     10.40                hc3806b6_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    10.0.0          py311h0b84326_0    conda-forge
pip                       23.2.1          py311h06a4308_0
pixman                    0.40.0               h7f8727e_1
platformdirs              2.5.2           py311h06a4308_0
pluggy                    1.0.0           py311h06a4308_1
ply                       3.11            py311h06a4308_0
pooch                     1.4.0              pyhd3eb1b0_0
poppler                   23.05.0              hd18248d_1    conda-forge
poppler-data              0.4.11               h06a4308_1
postgresql                15.3                 hd458b1d_1    conda-forge
poyo                      0.5.0              pyhd3eb1b0_0
proj                      9.2.1                ha643af7_0    conda-forge
prompt-toolkit            3.0.36          py311h06a4308_0
psutil                    5.9.0           py311h5eee18b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pulseaudio-client         16.1                 hb77b528_4    conda-forge
pure_eval                 0.2.2              pyhd3eb1b0_0
pyaez                     2.1                pyhd8ed1ab_0    conda-forge
pycodestyle               2.10.0          py311h06a4308_0
pycparser                 2.21               pyhd3eb1b0_0
pydocstyle                6.3.0           py311h06a4308_0
pyflakes                  3.0.1           py311h06a4308_0
pygments                  2.15.1          py311h06a4308_1
pylint                    2.16.2          py311h06a4308_0
pylint-venv               2.3.0           py311h06a4308_0
pyls-spyder               0.4.0              pyhd3eb1b0_0
pyopenssl                 23.2.0          py311h06a4308_0
pyparsing                 3.0.9           py311h06a4308_0
pyproj                    3.6.0           py311ha169711_1    conda-forge
pyqt                      5.15.7          py311ha74522f_3    conda-forge
pyqt5-sip                 12.11.0         py311hcafe171_3    conda-forge
pyqtwebengine             5.15.7          py311ha10a086_3    conda-forge
pyrsistent                0.18.0          py311h5eee18b_0
pysocks                   1.7.1           py311h06a4308_0
python                    3.11.4          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2          py311h06a4308_0
python-lsp-black          1.2.1           py311h06a4308_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.7.2           py311h06a4308_0
python-slugify            5.0.2              pyhd3eb1b0_0
python_abi                3.11                    3_cp311    conda-forge
pytoolconfig              1.2.5           py311h06a4308_1
pytz                      2022.7          py311h06a4308_0
pyxdg                     0.27               pyhd3eb1b0_0
pyyaml                    6.0             py311h5eee18b_1
pyzmq                     25.1.0          py311h6a678d5_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.2.2           py311h06a4308_0
qt-main                   5.15.8              h01ceb2d_12    conda-forge
qt-webengine              5.15.8               h27f4a20_2    conda-forge
qtawesome                 1.2.2           py311h06a4308_0
qtconsole                 5.4.2           py311h06a4308_0
qtpy                      2.2.0           py311h06a4308_0
rarfile                   4.0                pyh9f0ad1d_0    conda-forge
rasterio                  1.3.8           py311h41e4db2_0    conda-forge
readline                  8.2                  h5eee18b_0
requests                  2.31.0          py311h06a4308_0
rioxarray                 0.14.1             pyhd8ed1ab_0    conda-forge
rope                      1.7.0           py311h06a4308_0
rtree                     1.0.1           py311h06a4308_0
scikit-learn              1.2.2           py311h6a678d5_1
scipy                     1.10.1          py311h08b1b3b_1
secretstorage             3.3.1           py311h06a4308_1
setuptools                68.0.0          py311h06a4308_0
shapely                   2.0.1           py311h54d622a_1    conda-forge
sip                       6.7.9           py311hb755f60_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.10               h9fff704_0    conda-forge
snowballstemmer           2.2.0              pyhd3eb1b0_0
snuggs                    1.4.7              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    5.0.2           py311h06a4308_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.4.3           py311h38be061_0    conda-forge
spyder-kernels            2.4.3           py311h06a4308_0
sqlite                    3.41.2               h5eee18b_0
stack_data                0.2.0              pyhd3eb1b0_0
tbb                       2021.8.0             hdb19cb5_0
testpath                  0.6.0           py311h06a4308_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
three-merge               0.1.1              pyhd3eb1b0_0
tiledb                    2.13.2               hd532e3d_0    conda-forge
tinycss2                  1.2.1           py311h06a4308_0
tk                        8.6.12               h1ccaba5_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1           py311h06a4308_0
tomlkit                   0.11.1          py311h06a4308_0
tornado                   6.2             py311h5eee18b_0
traitlets                 5.7.1           py311h06a4308_0
tzcode                    2023c                h0b41bf4_0    conda-forge
tzdata                    2023c                h04d1e81_0
ujson                     5.4.0           py311h6a678d5_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.16         py311h06a4308_0
watchdog                  2.1.6           py311h06a4308_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1           py311h06a4308_1
whatthepatch              1.0.2           py311h06a4308_0
wheel                     0.38.4          py311h06a4308_0
wrapt                     1.14.1          py311h5eee18b_0
wurlitzer                 3.0.2           py311h06a4308_0
xarray                    2023.6.0        py311h06a4308_0
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xerces-c                  3.2.4                h8d71039_2    conda-forge
xkeyboard-config          2.39                 hd590300_0    conda-forge
xorg-compositeproto       0.4.2             h7f98852_1001    conda-forge
xorg-damageproto          1.2.1             h7f98852_1002    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxcomposite        0.4.6                h0b41bf4_1    conda-forge
xorg-libxdamage           1.1.5                h7f98852_1    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrandr            1.5.2                h7f98852_1    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
xorg-randrproto           1.5.0             h7f98852_1001    conda-forge
xorg-recordproto          1.14.2            h7f98852_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-util-macros          1.19.0               h27cfd23_2
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007
xyzservices               2022.9.0        py311h06a4308_1
xz                        5.4.2                h5eee18b_0
yaml                      0.2.5                h7b6447c_0
yapf                      0.31.0             pyhd3eb1b0_0
zeromq                    4.3.4                h2531618_0
zipp                      3.11.0          py311h06a4308_0
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hc292b87_0

All the best

Tony

------------------------<>---------------------------
Tony Payne
School of Geographical Sciences,
University of Bristol,
Bristol BS8 1SS, UK.
Telephone:  +44 117 455 3778
Email: ***@***.***
------------------------<>---------------------------

**Comment by antony-john-payne** [comment]
Hi

The problem seems to have gone away. Agreed, I think my problem had something to do with the numba version that I am using.

At the moment, numba 0.57.1 is working.


All the best

Tony

------------------------<>---------------------------
Tony Payne
School of Geographical Sciences,
University of Bristol,
Bristol BS8 1SS, UK.
Telephone:  +44 117 455 3778
Email: ***@***.***
------------------------<>---------------------------
